apiVersion: v1
kind: Pod
metadata:
  name: example-pod
spec:
  containers:
  - name: example-container
    image: nginx
    envFrom:
    - configMapRef:
        name: example-configmap



#env
envFrom:
  - configMapRef:
      name: app-confi

#Single env
env:
  - name: APP_COLOR
    valueFrom:
        configMapKeyRef:
          name: app-config
          key: APP_COLOR

#Volume
volumes:
  - name: app-config-volume
    configMap:
      name: app-config