apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
    - name: my-container
      image: nginx
      envFrom:
        - secretRef:
            name: my-secret



#env
envFrom:
  - secretRef:
      name: app-config



#Single env
env:
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: app-secret
        key: DB_Password



#Volume
volumes:
  - name: app-secret-volume
    secret:
      secretName: app-secret

