apiVersion: v1
kind: Pod
metadata:
  name: yellow
  labels:
    name: yellow
spec:
  containers:
    #container 1
    - name: lemon
      image: busybox

    #container 2
    - name: gold
      image: redis
