apiVersion: v1
kind: Pod
metadata:
  name: bee
  labels:
    app: test
spec:
  containers:
  - name: nginx
    image: nginx

  tolerations:
  - key: "spray"
    operator: "Equel"
    value: "mortein"
    effect: "NoSchedule"
